
unsafe impl Send for Key {}

#[derive(Debug, PartialEq)]
pub enum Key{
    Char(char),
    Ctrl,
    Alt,
    Shift,
    Escape,
    Backspace,
    Left,
    Right,
    Up,
    Down,
    Enter,
    Num(u8)
}

pub fn num_to_key(key: u32) -> Option<Key>{
    //If the number is big, we only need the first four numbers
    let mut key = key;
    if key > 10_000 {
        key /= 1000;

    }

    match key{
        4259 => Some(Key::Char('A')),
        4325 => Some(Key::Char('B')),
        4390 => Some(Key::Char('C')),
        4456 => Some(Key::Char('D')),
        4522 => Some(Key::Char('E')),
        4587 => Some(Key::Char('F')),
        4653 => Some(Key::Char('G')),
        4718 => Some(Key::Char('H')),
        4784 => Some(Key::Char('I')),
        4849 => Some(Key::Char('J')),
        4915 => Some(Key::Char('K')),
        4980 => Some(Key::Char('L')),
        5046 => Some(Key::Char('M')),
        5111 => Some(Key::Char('N')),
        5177 => Some(Key::Char('O')),
        5242 => Some(Key::Char('P')),
        5308 => Some(Key::Char('Q')),
        5373 => Some(Key::Char('R')),
        5439 => Some(Key::Char('S')),
        5505 => Some(Key::Char('T')),
        5570 => Some(Key::Char('U')),
        5636 => Some(Key::Char('V')),
        5701 => Some(Key::Char('W')),
        5767 => Some(Key::Char('X')),
        5832 => Some(Key::Char('Y')),
        5898 => Some(Key::Char('Z')),
        6357 => Some(Key::Char('a')),
        6422 => Some(Key::Char('b')),
        6488 => Some(Key::Char('c')),
        6553 => Some(Key::Char('d')),
        6619 => Some(Key::Char('e')),
        6684 => Some(Key::Char('f')),
        6750 => Some(Key::Char('g')),
        6815 => Some(Key::Char('h')),
        6881 => Some(Key::Char('i')),
        6946 => Some(Key::Char('j')),
        7012 => Some(Key::Char('k')),
        7077 => Some(Key::Char('l')),
        7143 => Some(Key::Char('m')),
        7209 => Some(Key::Char('n')),
        7274 => Some(Key::Char('o')),
        7340 => Some(Key::Char('p')),
        7405 => Some(Key::Char('q')),
        7471 => Some(Key::Char('r')),
        7536 => Some(Key::Char('s')),
        7602 => Some(Key::Char('t')),
        7667 => Some(Key::Char('u')),
        7733 => Some(Key::Char('v')),
        7798 => Some(Key::Char('w')),
        7864 => Some(Key::Char('x')),
        7929 => Some(Key::Char('y')),
        7995 => Some(Key::Char('z')),
        2097 => Some(Key::Char(' ')),
        3014 => Some(Key::Char('.')),
        2162 => Some(Key::Char('!')),
        4194 => Some(Key::Char('@')),
        2293 => Some(Key::Char('#')),
        2359 => Some(Key::Char('$')),
        2424 => Some(Key::Char('%')),
        6160 => Some(Key::Char('^')),
        2490 => Some(Key::Char('&')),
        2752 => Some(Key::Char('*')),
        2621 => Some(Key::Char('(')),
        2686 => Some(Key::Char(')')),
        2883 => Some(Key::Char(',')),
        3932 => Some(Key::Char('<')),
        4063 => Some(Key::Char('>')),
        3866 => Some(Key::Char(';')),
        3801 => Some(Key::Char(':')),
        2555 => Some(Key::Char('\'')),
        2228 => Some(Key::Char('"')),
        6029 => Some(Key::Char('\\')),
        8126 => Some(Key::Char('|')),
        3080 => Some(Key::Char('/')),
        4128 => Some(Key::Char('?')),
        29 => Some(Key::Ctrl),
        56 => Some(Key::Alt),
        42 => Some(Key::Shift),
        1769 => Some(Key::Escape),
        75 => Some(Key::Left),
        77 => Some(Key::Right),
        72 => Some(Key::Up),
        80 => Some(Key::Down),
        851 => Some(Key::Enter),
        524 => Some(Key::Backspace),
        3211 => Some(Key::Num(1)),
        3276 => Some(Key::Num(2)),
        3342 => Some(Key::Num(3)),
        3407 => Some(Key::Num(4)),
        3473 => Some(Key::Num(5)),
        3538 => Some(Key::Num(6)),
        3604 => Some(Key::Num(7)),
        3670 => Some(Key::Num(8)),
        3735 => Some(Key::Num(9)),
        3145 => Some(Key::Num(0)),
        _ => None
    }
}
